server:
  port: 20001

spring:
  application:
    name: mall-auth
  cloud:
    gateway:
      routes: #配置路由路径
        - id: mall-auth
          uri: http://localhost:20001
          predicates:
            - Path=/mall-auth/**
          filters:
            - StripPrefix=1

version: @pom.version@

mall:
  white:
    path:
#      - /mall-auth/test/**
      - /**/favicon.ico
