server:
  port: 20002

spring:
  application:
    name: mall-user
  datasource:
    url: jdbc:mysql://39.102.83.104:23306/mall-user?useUnicode=true&useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: tiger
  redis:
    host: http://localhost
    port: 6379
    database: 0
    password: root

#swagger:
swagger:
  basePackage: com.codezzz.user.controller


# custom path for swagger-ui
#springdoc:
#  swagger-ui:
#    path: doc.html
#    operations-sorter: method
#    #custom path for api docs
#    url: /doc/openapi.json

service-name: malluser

service-prefix: api/${service-name}